### 1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]


In [22]:
import hashlib
import os

def scanDuplicates(path):
    dirList = os.listdir(path)

    hashList = []
    duplicate = []
    pathDirDict = {path : dirList}


    for i in dirList:
        if '.' not in i:
            pathDirDict[path + '\\' +  i] = os.listdir(path + '\\' + i)

    for i in pathDirDict:
        for j in pathDirDict[i]:
            if '.txt' in j:

                fileObj = open(i + '\\' + j)

                str1 = fileObj.read().encode()

                hash1 = hashlib.sha256(str1)

                if hash1.hexdigest() in hashList:
                    duplicate.append(i + '\\' + j)
                else:
                    hashList.append(hash1.hexdigest())

                fileObj.close()
                
    return duplicate

def removeDuplicate(duplicate):
    for i in duplicate:
        os.remove(i)
    print("Duplicates Remvoed!")
    

path = input("Enter path of the first file: ")

duplicates = scanDuplicates(path)

print("Duplicates:", duplicates)

removeDuplicate(duplicates)

print("Duplicates Remaining:", scanDuplicates(path))


Enter path of the first file: C:/Users/patyagi/Tek_python
Duplicates: ['C:/Users/patyagi/Tek_python\\Dit.txt', 'C:/Users/patyagi/Tek_python\\F2.txt', 'C:/Users/patyagi/Tek_python\\F3.txt', 'C:/Users/patyagi/Tek_python\\Hello2.txt', 'C:/Users/patyagi/Tek_python\\xyz\\Dit2.txt', 'C:/Users/patyagi/Tek_python\\xyz\\F4.txt']
Duplicates Remvoed!
Duplicates Remaining: []


### 2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]


In [3]:
import random
import string

password=[]
for i in range(0,2):
    password.append(random.choice(string.ascii_lowercase))
    password.append(random.choice(string.digits))
password.append(random.choice(string.ascii_uppercase))
password.append(random.choice(string.punctuation))
random.shuffle(password)
print("".join(password))

vG0\8u


### 3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [11]:
import numpy as np
def prime(pos):
    c=0
    for i in range(2,int(pos/2)+1):
        if pos %i ==0:
            c=1
            break
    if c==0:
        return True
    else:
        return False
n=int(input())
m=int(input())
arr=np.arange(n*m).reshape(n,m)
print(arr)
pos=0
for i in range(n):
    for j in range(m):
        if prime(pos):
            arr[i][j]=arr[i][j]*arr[i][j]*arr[i][j]
        pos+=1
print(arr)

5
5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[    0     1     8    27     4]
 [  125     6   343     8     9]
 [   10  1331    12  2197    14]
 [   15    16  4913    18  6859]
 [   20    21    22 12167    24]]


### 4.	Python program to get the sum of every cubed value and its previous integer. 

In [13]:
import numpy as np
number =0
arr2=np.empty_like(arr)
for i in range(n):
    for j in range(m):
        if number !=0 and ((arr[i][j]/number)/number) ==number:
            arr2[i][j] =arr[i][j] +arr[i][j-1]
        else:
            arr2[i][j]=arr[i][j]
        number+=1
print(arr2)

[[    0     1     9    35     4]
 [  134     6   349     8     9]
 [   10  1341    12  2209    14]
 [   15    16  4929    18  6877]
 [   20    21    22 12189    24]]


### 5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
               arr2[] = [2, 3, 5, 6]


In [14]:
import numpy as np
arr1 = np.array([1, 3, 4, 5, 7])
arr2 = np.array([2, 3, 5, 6])
arr = np.intersect1d(arr1, arr2)
print (arr)


[3 5]


### 6.Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [15]:
import numpy as np
arr=np.zeros((7,7),dtype='int16')
val=1
for i in range(7):
    for j in range(7):
        arr[i][j]=7*val
        val+=1
print(arr)
print("\nLast element of the array is:",arr[-1][-1])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]

Last element of the array is: 343


###  7.	Checker Board Patten using Numpy:

    [   1   0   1   0   1   0   1
        0   1   0   1   0   1   0
        1   0   1   0   1   0   1
        0   1   0   1   0   1   0
        1   0   1   0   1   0   1  ]


In [27]:
import numpy as np
n=int(input("Enter no of rows:"))
m=int(input("Enter no of columns:"))
arr=np.ones((n,m),dtype='int8')
arr[1::2,::2]=0
arr[::2,1::2]=0
print(arr)

Enter no of rows:5
Enter no of columns:7
[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


### 8.	Create a given Matrix:
    [  A,     B,     C,     D
       E,     F,     G,     H
       I,     J,     K,     L 
       M,     N,     O,     P
       Q,     R,     S,     T
       U,     V,     W,     X ]
       
       Replace all the vowels by np.nan
       A, E, I, O U  -- >  np.nan
       Return the count of the missing values



In [20]:
import string
list1=list(string.ascii_uppercase)[:-2]
array=np.array(list1).reshape(4,6)
list1=array.tolist()
vowels=['A','E','I','O','U']
for i in range(0,len(list1)):
    list1[i]=[np.nan if item in vowels else item for item in list1[i]]
print(np.array(list1))
    
sum=0
for i in list1:
    sum+=i.count(np.nan)
    
print("\n",sum)

[['nan' 'B' 'C' 'D' 'nan' 'F']
 ['G' 'H' 'nan' 'J' 'K' 'L']
 ['M' 'N' 'nan' 'P' 'Q' 'R']
 ['S' 'T' 'nan' 'V' 'W' 'X']]

 5
